# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10 on 2016-10-24 17:36
=======
# Generated by Django 1.10 on 2016-10-31 05:09
>>>>>>> 33cf1ca3b503466274e50c42c2bfecff2f673b29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0008_alter_user_username_max_length'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 33cf1ca3b503466274e50c42c2bfecff2f673b29
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
<<<<<<< HEAD
=======
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
>>>>>>> 33cf1ca3b503466274e50c42c2bfecff2f673b29
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
                ('dimX', models.IntegerField(default=400)),
                ('dimY', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('header', models.CharField(max_length=60)),
                ('style', models.CharField(max_length=30)),
                ('stylesheet', models.CharField(max_length=100)),
                ('frontpage', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Blog')),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
=======
>>>>>>> 33cf1ca3b503466274e50c42c2bfecff2f673b29
        migrations.AddField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Profile'),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='photos',
=======
            model_name='content',
>>>>>>> 33cf1ca3b503466274e50c42c2bfecff2f673b29
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio'),
        ),
        migrations.AddField(
            model_name='blog',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio'),
        ),
    ]
