# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='frontpage',
            field=models.BooleanField(default=False),
        ),
    ]
