# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 15:00
from __future__ import unicode_literals

import os
from sys import path
from django.core import serializers
from django.db import migrations, models
from datetime import date
from django.core.management import call_command

def loaddata(apps, schema_editor):
    call_command('loaddata','initial_users.json')
class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
    ]
