# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(default=None, upload_to='Portfolio', verbose_name='main'),
        ),
    ]
