# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20161102_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='header',
            field=models.CharField(max_length=150),
        ),
    ]
